pyvisa/pyvisa

pyvisa/resources/resource.py

When trying to access the 'interface_type' property of my opened resource, I got the following error:
```  File "C:\Python27\lib\site-packages\pyvisa\resources\resource.py", line 145, in interface_type
self.resource_name).interface_type
AttributeError: 'tuple' object has no attribute 'interface_type' ```
Indexing the first element of that tuple fixed the problem.

Fixed access to the interface_type property

---

pyvisa/ctwrapper/functions.py
pyvisa/resources/resource.py

This improves the locking stuff.
- fixes a timeout calculation
- Changed the value for default and the return value for the lock method.
These are breaking change, but they should have minimal effect I think (only people that specifically requested a timeout of None will see the behavior change, not specifying it will behave the same way; and using a python value instead of ctypes should alow different backend to work the same way, and allows the use of the return value directly as the requested_key for another lock call).
- added lock_excl and a lock_context (to be used with with statements)

Add lock exclusive

---

pyvisa/util.py

the line `values = inst.query_ascii_values('CURV?', container=numpy.array)`
from the documentation does not work as expected: it returns an 0-dim numpy
array with a generator object as content.
example code to verify:
```python
from __future__ import print_function, unicode_literals
import numpy
from pyvisa import util
values = util.from_ascii_block("1,2,3,4", container=numpy.array)
print(values)
print(len(values))
```
will throw a `TypeError: len() of unsized object` on 2.7 and 3.4. It works for
binary values as these are parsed into a tuple with struct.unpack so
`numpy.array()` works as expected.
This commit makes query_binary_values and query_ascii_values behave
consistently but will construct a temporary list.

Make container=numpy.array work consistently

---

pyvisa/errors.py
pyvisa/highlevel.py

This is a suggested fix for the error I encountered (see issue 136).
Improves error handling (raise instead of raise e and delayed caching)
And fix the unicode handling problem by removing future import of unicode_literals.
(The error messages from the operating system are not unicode in python 2.7 (windows7), but can contain non-ascii characters. Also the windows library loading requires a string not a unicode, at least in my version.)
There might be other modules where unicode_literals might be removed.

Fix for issue 136: UnicodeDecodeError on wrong file for library load

---

pyvisa/resources/messagebased.py

When a serial instruments is set to use the VI_ATTR_TERMCHAR for
VI_ATTR_ASRL_END_IN (default) then it uses the value in VI_ATTR_TERMCHAR.
By default read_termination is None, and VI_ATTR_TERMCHAR ends up being the
default value of LF. But when switching around the read_termination to
something (like CR) then coming back to None will leave VI_ATTR_TERMCHAR
in a different state that at the start (with CR instead of LF) and this will
change the behavior of read on serial instruments.
The above change always makes VI_ATTR_TERMCHAR LF when read_termination is set
to None.

Fix reseting of line termination for serial

---

pyvisa/highlevel.py
pyvisa/resources/gpib.py
pyvisa/resources/resource.py

This completes the changes to the handlers (I might add some doc at a later time if I have time)
It adds wait_on_event to all resources.
Cleans up the duplicates and uses the newly available methods in resources for gpib
Moves __switch_events_off to resources
And properly cleanup the visa handlers (and the dictionary cache) upon session close.
This way, closing a session will do a proper cleanup of the events/handlers so most people will not have to use the uninstall/disable interface. In particular I did not try to make uninstall work automatically (install_handler could return and object that cleans up when erased, like I did for wait_on_event, but that would require keeping track of the returned value by the user which not everyone needs to do right now. Since uninstall is not needed …

Improve handlers 2nd part

---

pyvisa/ctwrapper/functions.py

ctwrapper/functions lock was failing when access_key was None

lock_excl bug fix

---

pyvisa/resources/gpib.py
pyvisa/resources/messagebased.py
pyvisa/resources/tcpip.py
pyvisa/resources/usb.py

control_ren can be used by more than gpib (can change local/remote state of instrument on usb and tcpip). I created a mixin and used it where I know it will work.
Another option would be to just put control_ren in MessageBasedResource.

Moved control_ren to a mixin and added it to USB, GPIB and TCPIP

---

pyvisa/resources/resource.py

WaitResponse is initialized with an event_type of 0 for a timeout in
wait_on_event. This was causing errors.
So replaced that special case with None.

Fix a not a invalid EventType bug

---

docs/resources.rst

it previously stated RegisterBasedResource twice, which didn't make sense and later referenced MessageBasedResource which wasn't mentioned before.

dedup and change instrument classes

---

pyvisa/resources/resource.py

If wait_on_event is called with capture_timeout=True and a timeout occurs we try to create a WaitResponse object with 0 as the event type. This will fail, as 0 is not part of the Enum. Create the object with the input event type instead.

wait_on_event: create WaitResponse object with correct event_type

---

pyvisa/highlevel.py

Using ResourceManager.resource_info returned inconsistent results
between the NI-VISA backend vs other backends which didn't extend
visalib.parse_resource_extended (e.g. PyVISA-sim) and code relying
on the "normalization" behavior of resource_info.resource_name
would not work.

fix(highlevel): added resource_name to parse_resource_extended

---

pyvisa/resources/resource.py

This makes it possible to do `with rm.open_resource('...') as res: ...`.

Turned Resource into a context manager

---

pyvisa/errors.py
pyvisa/testsuite/test_errors.py

Fixes a bug when trying to pickle/unpickle pyvisa exceptions. For example, previously it was not possible to send an exception instance from one process to another through a pipe.

Enable Exceptions to be pickled/unpickled

---

docs/shell.rst
visa.py

in `visa` command line tool it was not possible to setup backend, ni-visa  is used as default.
New option is supported (short and long form):
```
-b BACKEND
--backend BACKEND
```
Examples
`python -m visa shell` runs as currently supported functionality
`python -m visa -b pyshell` runs with `python-py` backend, useful when ni-visa not installed
`python -m visa -b sim shell` runs with `python-sim` backend, useful for resting pyvisa simulator configuration
(related to #195)

visa command line can use non-default backend

---

docs/shell.rst
pyvisa/shell.py

Added support for termination character (read_termination) setup / read into shell (visa command line tool).
To display termination character
```
(open) termchar
```
To set termination character (read and write)
```
(open) termchar <termchar> [<termchar>]
```
`<termchar>` is one of `CR`, `LF`, `CRLF`, `NUL`.
To disable termination character, `None` shall be used
If two termchars are provided, first is read termination character and second is write termination character

shell: support for 'termchar' command

---

.travis.yml

This will avoid getting one stupid failure everytime bors run.

Build only the branches required by bors

---

pyvisa/shell.py

Fix based on comment in #285
> One minor thing I forgot before merging, to check that a key exist inside a dictionary the following syntax is more often used (compared to has_key): `if key in mydict: ...`
Also checking of read and write termination improved

Fixes in shell.py (reported in #285)

---

pyvisa/highlevel.py

`pyvisa.highlevel.get_wrapper_class` iterates through the discovered backends to find one that matches the requested name. This iteration is performed in `list_backends()` and uses `pkgutil.iter_modules()`. If a backend with the matching name is found, the code attempts to dynamically import it.
When PyInstaller "freezes" modules, they can't be found by `pkgutil` and friends, which means that even if you freeze pyvisa and pyvisa-py, the pyvisa-py backend can't be found because `iter_modules` can't see it.
This PR eliminates the search loop, which might not have been strictly necessary. It simply attempts to do the dynamic import. Success and failure are both handled identically to the previous version, but failure is observed when an ImportError is raised.
As a result, PyInstaller can now …

Prefer import to pkgutil.iter_modules(), support PyInstaller

---

.travis.yml
docs/conf.py
docs/rvalues.rst
pyvisa/compat/__init__.py
pyvisa/compat/struct.py
pyvisa/constants.py
pyvisa/resources/messagebased.py
pyvisa/testsuite/__init__.py
pyvisa/testsuite/test_rname.py
pyvisa/testsuite/test_util.py
pyvisa/util.py

~~This is WIP and untested so far~~ This has now been fully tested locally:
- implement HP binary header following @thliebig work ~~(I plan on adding tests)~~ done
- fix the issue in write_ascii_values by properly encoding the values in `utils.to_ascii_block` (closes #252)
- add noisy warnings to encourage migrations to new api for values reading/writing
- uniformize the API for reading values by providing read_ascii_values and read_binary_values
Also make all file concerned by the update be PEP8 compliant.
I hope to complete and test this before Christmas, but anybody is welcome to test and review.

Message based improvements

---

pyvisa/rname.py
pyvisa/testsuite/test_rname.py

The documented value in the header is \xFFFF but used in resource string it does crash. The Matworks link suggest using 0 in the absence of secondary address which works (tested on one instrument) and seems more logical.

rname: fix default gpib secondary address

---

docs/configuring.rst
pyvisa/highlevel.py

This fixes #334.
I also have a commit prepared that adds `pyvisa-py` as a dependency to setup.py, but I don't know if you want that. If we include it, it's guaranteed that people will always have a backend available even if the NI one isn't installed, so i lean towards doing that. Please comment on that @MatthieuDartiailh (*edit: I have pushed that commit to the PR now, it should be easy to not included it if desired*)
I tested this on my local machine (without the NI library). pyvisa-py gets selected successfully:
```
import pyvisa
pyvisa.ResourceManager()
Out[2]: <ResourceManager(<VisaLibrary('unset')>)>
```
If neither NI nor pyvisa-py are around, we get (with debug output enabled)
```
pyvisa.ResourceManager()
DEBUG:pyvisa:No visa library specified, trying to find alternatives. …
```

For default backend, use pyvisa-py if the NI binary cannot be found.

---

pyvisa/errors.py
pyvisa/testsuite/test_errors.py

I am not yet sure that this is without consequences, but I suppose it is. Any opinion ?

pyvisa: make exception hashable by removing exception __eq__

---

CHANGES
pyvisa/resources/messagebased.py

Solves #348.
Adding expect_termination argument with read_binary_values and query_binary_values allows to get back to the behavior of these methods as it was in pyvisa 1.8 where the very last read termination was not accounted for. Forced accounting for it makes this method raise a time out exception in some instruments.
@MatthieuDartiailh

Add expect_termination to read_binary_values (issue 348)

---

CHANGES
pyvisa/resources/usb.py

Fixing missing argument for USBInstrument.usb_control_out. Homogeneous naming for USBInstrument: usb_control_out -> control_out. Add usb_control_out with deprecated warnings.

bugfix for missing arguments in USBInstrument methods (issue 352)

---

CHANGES
pyvisa/__init__.py

Without breaking compatibility with older code I have kept the log_to_screen() function and added a more generic log() function to be able to redirect the specific pyvisa logging output to file (in the case an application is already using stderr for other purposes).

Added possibility to redirect logging to file

---

AUTHORS
CHANGES
pyvisa/constants.py

Fix for issue #370 .
The enums `StatusCode.error_nonsupported_offset` and `StatusCode.error_nonsupported_offset_alignment` had the same value of `VI_ERROR_NSUP_OFFSET`, and `VI_ERROR_NSUP_ALIGN_OFFSET` was not used.
To ensure this does not happen again,, all enum classes in the `pyvisa.constants` modules have been decorated with the [`enum.unique`](https://docs.python.org/3.5/library/enum.html?highlight=enum#enum.unique) class decorator.

Fixed duplicate StatusCode value and made all enums unique

---

CHANGES
pyvisa/highlevel.py

The changes (commit f2d69892) in open_visa_library to use either a NI backend or if not available the pyvisa-py are nice except they seem a bit too broad.
If somebody specifies a file (dll) to use when opening the ResourceManager, it still looks for the standard dll to see if they are available (_get_default_wrapper()). Therefore, if none of the standard dll are available (like visa32.dll, visa64.dll on windows) but a correct other dll is given (like agvisa32.dll for the agilent visa library) it still fails.
It is probably a rare condition to be in but it is not impossible.
This PR fixes that.

Use ni backend when specifying a file in open_visa_library

---

CHANGES
pyvisa/resources/gpib.py

Instead we use perf_counter.
Closes #394

Remove use of time.clock under Python 3.3+

---

CHANGES
docs/source/introduction/communication.rst
pyvisa/highlevel.py
pyvisa/resources/resource.py

Based on @ruggiamp suggestion in #414, add a `list_opened_resources` method to the resource manager returning a snapshot of the opened resources. The documentation has been updated to add an example of its usage.
Also in the Resource class we use consistently the resource name stored in the private attribute (`_resource_name`) to avoid relying on the VisaLibrary object to get it. This should fix issues such as https://github.com/pyvisa/pyvisa-py/issues/151.
@ruggiamp please test if you can (I already tested locally).
@hgrecco @tivek please review if you can.

ResourceManager.list_opened_resources

---

CHANGES
docs/source/introduction/rvalues.rst
pyvisa/resources/messagebased.py
pyvisa/util.py

This address a couple of issues and is based on #430 :
- `chunk_size` appears to be able to fix the issue seen in #431, even if at the time being the underlying issue is not clear but is likely outside of PyVISA (whether it is a VISA implementation issue or an instrument specific is unclear)
- `data_length` fills a gap by providing a way to get in a controlled manner binary data from instrument that use a protocol that do not report how many bytes will be transferred (such as the Keithley 2000 which is commonly used with PyVISA). **I still have some work to do on the utility functions to handle this properly**
The documentation has been updated to reflect those changes.  The changelog must be updated before merging. @bjaraujo if you can test and review, I would greatly appreciate it.

Add `chunk_size` and `data_length` to `read/query_binary_values`

---

CHANGES
docs/source/advanced/architecture.rst
docs/source/advanced/backends.rst
docs/source/introduction/communication.rst
docs/source/introduction/configuring.rst
docs/source/introduction/shell.rst
pyvisa/__init__.py
pyvisa/ctwrapper/__init__.py
pyvisa/ctwrapper/highlevel.py
pyvisa/highlevel.py
visa.py

I made change in:
- 'highlevel.py' more precisely in list_backends(),  get_wrapper_class() and _get_default_wrapper() functions. 
- 'visa.py'
- Docs files
To my mind it's enough. 
Of course, I tested it as much as I could.
I'm not sure about docs, please double check it.

Change ni to ivi backend name "Reduce bias towards National Instruments (issue 455)"

---

docs/source/introduction/communication.rst

There is a note that mistakenly called the `delay` parameter of the `query*` methods `query`.

Fix `delay` parameter for the query* methods.

---

pyvisa/highlevel.py

(Related to pyvisa/pyvisa-py#244)

docs: mention that ResourceManager.list_resources() may not return open devices

---

azure-pipelines.yml
pyvisa/testsuite/keysight_assisted_tests/messagebased_resource_utils.py

tests: add a test for clear on message based resources

---

.pre-commit-config.yaml
CHANGES
pyvisa/highlevel.py
pyvisa/testsuite/test_highlevel.py

This typically happens for serial resource on Linux where we end up ASRL/dev/tty0::INSTR. Without this change users have to specify the resource class they want.

highlevel: avoid returning a generic resource info for a non-int board

---

CHANGES
pyvisa/resources/gpib.py

Those methods belong exclusively to GPIB::INTFC

gpib: deprecate methods that were mistakenly added to GPIB::INSTR

---

CHANGES
pyvisa/ctwrapper/highlevel.py

Correct the information for ctypes debug info (previously we were getting the manufacturer name 3 times !)

ctwrapper: fix debug info collection

---

.github/workflows/ci.yml
.gitignore
CHANGES
docs/source/introduction/communication.rst
pyvisa/highlevel.py
pyvisa/resources/messagebased.py
pyvisa/resources/usb.py
pyvisa/shell.py
pyvisa/testsuite/keysight_assisted_tests/messagebased_resource_utils.py
pyvisa/testsuite/keysight_assisted_tests/test_resource_manager.py
pyvisa/testsuite/keysight_assisted_tests/test_tcpip_resources.py
pyvisa/testsuite/test_cmd_line_tools.py
pyvisa/testsuite/test_util.py
pyvisa/thirdparty/prettytable.py
pyvisa/util.py

WAIT for Keysight buildbot to be up and running again.

Fix reading ieee empty block

---

CHANGES
pyvisa/attributes.py
pyvisa/constants.py

Per suggest in pyvisa/pyvisa-py#316, updating ControlFlow enum from
IntEnum to IntFlag.

Int flag update for control flow issue pyvisa/pyvisa-py#316

---

.github/workflows/ci.yml
CHANGES
pyvisa/testsuite/keysight_assisted_tests/__init__.py
pyvisa/testsuite/keysight_assisted_tests/messagebased_resource_utils.py
pyvisa/testsuite/test_util.py
pyvisa/util.py

Improve write_binary_values by bypassing the struct module when possible

---

.github/workflows/ci.yml
pyvisa/rname.py
pyvisa/testsuite/test_rname.py

If a resource does not use a GPIB device secondary address, it should be fully omitted from the resource name rather than set to 0. Setting the secondary address to 0 can cause issues with old instruments (see #640) and also cause issues when using low-level GPIB protocols (can't find the issue ATM).
@sixtemesseven could you review and tests as you offered to do in #640

GPIB improve secondary address handling

---

CHANGES
pyvisa/cmd_line_tools.py
pyvisa/testsuite/test_cmd_line_tools.py

Removes a double call to `shell.main` in `cmd_line_tools.py`.
Before the change, calling `exit` from `pyvisa-shell` results in a re-entry of the command loop.  `exit` has to be called twice.
After this change:

Remove duplicate call to shell.main

---

CHANGES
pyvisa/ctwrapper/types.py

Corrected ViBusAddress, ViBusSize, ViAttrState corrected as per VISA.h(from Include file for the VISA Library 7.2 specification)
Tested with register based instrument
Closes #724

Types  corrected as per  VISA 7.2 spec(visa.h)

---

CHANGES
pyvisa/resources/messagebased.py

Problem was, that the read_termination_context did not accept None for no read_termination.
Changes:
- Logic of `read_termination.setter` moved to a new method (without setting private attribute `_read_termination`).
- `read_termination_context` uses that new method to set the termination before and after yield.
Open question:
Right now, the private attribute `_read_termination` (returned by public property `read_termination`) remains the original one.
If you prefer, we could change that, such that the method looks this:
~~~python
def read_termination_context(self, value):
term = self.read_termination
yield
self.read_termination = term
~~~

read_termination_context uses read_termination logic

---

.pre-commit-config.yaml
pyvisa/rname.py
pyvisa/testsuite/test_rname.py

Split out of https://github.com/pyvisa/pyvisa/pull/733 since fix ended up being a bit involved.
`mypy` was complaining about bound typevar https://github.com/pyvisa/pyvisa/blob/df50969b3527ccfa28ae7e67b2be7468865bd3e2/pyvisa/rname.py#L99 being too loose, which was true. However, we couldn't just make `ResourceName` a dataclass since it'd bring a bunch of unneeded fields into children, which was breaking all of the logics.
I ended up separating things that needed to not be in a dataclass into a separate private parent class, with `ResourceName` becoming a dataclass as it should've been.
There are opportunities to make it a bit more elegant, but I'd rather discuss that separately.

Fix dataclass hierarchy uncovered by mypy

---

CHANGES
pyvisa/ctwrapper/highlevel.py
pyvisa/errors.py
pyvisa/testsuite/test_util.py
pyvisa/util.py

- Replaced `bitness` of libraries and python interpreter
- Removed unused `LibraryPath.is32bit`, `LibraryPath.is_64bit`, and `LibraryPath.bitness` methods
- Introduced AARCH64 as tested-for architecture
- Slightly updated detection logic
- Removed IA64 and linux universal binary test scenarios since they are unrealistic
- Removed `linux2/3` checking since it should not exist past Python 3.3
I am not entirely happy with current enum-based approach, but I still think enums are more appropriate in this case than magic dicts. Maybe we can re-use (renamed) PEMachineType for arch info.
I was also considering having actual fake binaries for all platforms/architectures we test for stored in test artifacts since current approach with mocking is quite brittle.
Please let me know if you had a …

Use architecture instead of `bitness` in `LibraryPath` and friends

---

CHANGES
pyvisa/resources/resource.py

The type annotation for `Resource.__enter__()` indicates that it returns the base class, `Resource`. If you narrow the resource type to a derived class before entering the context manager, entering the context manager casts it back to the base class.
The solution is to use a type var to specify that the return type is the same as the type of `self`.

resources: Update context manager type annotation to preserve derived type

---

paper.bib
paper.md

This PR applies general language edits for grammar, clarity, and tense for the JOSS paper submission in https://github.com/openjournals/joss-reviews/issues/5304.
These edits reflect my understanding as a reader, but if there are strong disagreements with them they very much can be revised &mdash; these are not editorial edicts. :+1:

fix: Apply language edits for clarity and tense

---

pyvisa/highlevel.py

Add a note in the docstring of ResourceManager.close to hint the user to the fact that this closes all shared resource manager connections.
Closes #742

mention session sharing in ResourceManager.close docstring

---

CHANGES
docs/source/introduction/shell.rst
pyvisa/cmd_line_tools.py
pyvisa/testsuite/test_cmd_line_tools.py

Fixes #773.
Add support for custom simulated instrument files when using `pyvisa-shell -b sim`:
```console
$ pyvisa-shell -b my_file.yaml@sim
```

Add support for custom simulated file backends in shell

---

CHANGES
pyvisa/highlevel.py

Closes #786 
@kimbyungnam can you test ?

highlevel: allow missing board number which is the case for VICP

---

CHANGES
pyvisa/testsuite/test_util.py
pyvisa/util.py

This PR adds very rudimentary tracking of dll paths we already added in order to prevent exceeding path length limit if we create `ResourceManager`s in a loop.

Prevent duplicate paths from being added to the DLL paths

---

CHANGES
pyvisa/cmd_line_tools.py

This commit adds `-v` (or `-vv` or `-vvv` or `-v -v` or `-v -v -v`) as command line flags that can be passed to `pyvisa-shell` such that WARN (`-v`), INFO (`-vv`), or DEBUG (`-vvv`) messages will be emitted when running the shell. This can help users understand why a device is not listed that they believe should be listed when using that tool. Guidance in documentation can be added (by me, in the near future) to tell users to utilize these options if things are not working correctly. As it stands now, `pyvisa-shell` just doesn't say anything, and the only way to get increased messages is to write a Python script to do this.
This commit, along with https://github.com/pyvisa/pyvisa-py/pull/423 in the pyvisa-py, (as soon as I also update documentation appropriately) will close #758 and I …

add -v cmdline flag to pyvisa-shell for warn/info/debug logging output

---

CHANGES
pyvisa/cmd_line_tools.py
pyvisa/testsuite/test_cmd_line_tools.py

pyvisa-shell and pyvisa-info have nothing in common besides being PyVISA CLI commands. Notice that all options are currently targeted for pyvisa-shell [1], even though argparse happily reports `--backend` and `-v` options for pyvisa-info as well. In addition to that, everything else in the shared `pyvisa_main()` is conditional on the given `command`.
Implement them separately, including the function body and argument handling. This effectively reduces the amount of code and complexity for having them available. It also enables proper handling of the commands documentation, including description line. If arguments ever needs to be shared by both commands, there can be a shared function that equally populate their parsers.
Parsers are created by standalone functions, so that other tools can …

cli: unshare pyvisa cli command implementation

---

CHANGES
pyproject.toml

Set 4.0.0 as the lower bound for `typing_extensions`

---

CHANGES
pyvisa/attributes.py

Since I never found a VICP spec I went with what pyvisa-py supports plus some that are supported by both TCPIP INSTR and SOCKET.

attributes: add VICP resources to supported attributes.

---

.pre-commit-config.yaml
CHANGES
pyvisa/resources/messagebased.py
pyvisa/testsuite/test_util.py
pyvisa/util.py

This PR adds the following:
* `parse_ieee_block_header` now supports decoding blocks ≥ 1 GB using hexadecimal length digit (Tektronix/LeCroy)
* New function `parse_rs_block_header` supports decoding blocks ≥ 1 GB using parentheses-delimited length (Rohde & Schwarz)
* New `header_fmt = "rs"` option added to `read/query_binary_values()`. Internally this first calls the function `parse_ieee_or_rs_block_header`, which detects whether the block length begins with a parentheses and then calls the `ieee` or `rs` parser as appropriate. This implementation is used because R&S only uses this format when the block length exceeds 1 GB, so it's best to use automatic detection rather than need to have the user explicitly know whether it is using the parentheses format or not
* Exposes the …

Add support for extended block lengths
