- pyvisa/constants.py
- pyvisa/ctwrapper/functions.py
- pyvisa/highlevel.py
- pyvisa/resources/resource.py
This is my first pull request on GitHub so pardon me if it is not done properly.
These are a list of commits to fix/improve the usage of events/handlers
> Improve handlers

- pyvisa/compat/struct.py
- pyvisa/util.py
create compact/struct.py to replace unicode literals with str() on python<2.7.8 and modify util.py to use this
> Compat struct

- pyvisa/attributes.py
- pyvisa/resources/resource.py
Added a flow_control attribute
And fix creation of empty attributes
> Fix attributes

- pyvisa/ctwrapper/functions.py
- pyvisa/highlevel.py
Added 64 bit function names to functions.py. Additionally, added 64 bit function calls in highlevel.py.
> 64 bit functions

- docs/shell.rst
- pyvisa/shell.py
added support for timeout setup / read into shell (visa command line tool)
To display timout
```
(open) timeout
```
To set timeout
```
(open) timeout 2400
```
> shell: support for 'timeout' command

- docs/configuring.rst
- pyvisa/highlevel.py
I implemented part of the idea from bug #194.
> Allow selecting backends by setting a environment variable

- pyvisa/resources/resource.py
- pyvisa/shell.py
converts value to python type based on visa attribute type.
Also return value from set_attribute is processed
Relates to #298
> Shell: set attribute processing

- pyvisa/attributes.py
> Ensure that __doc__ exists before adding to it.

- README
- docs/api/constants.rst
- docs/architecture.rst
- docs/backends.rst
- docs/conf.py
- docs/configuring.rst
- docs/faq.rst
- docs/getting.rst
- docs/getting_nivisa.rst
- docs/index.rst
- docs/tutorial.rst
Add mention of PyVISA-Py so that people do not believe they have to use NI VISA, update outdated links, and overall reformat the docs source files.
@ClundXIII could you give this a look and see if it fits your expectations (README, index.rst and getting.rst)
> docs: documentation update

- pyvisa/ctwrapper/cthelper.py
Resolves https://github.com/pyvisa/pyvisa/issues/379
> Resolve ResourceWarning: unclosed file" warnings

- CHANGES
- pyvisa/ctwrapper/highlevel.py
> Reworked search for library path to make it deterministic

- pyvisa/highlevel.py
- pyvisa/resources/resource.py
Closes #273 
Any review and tests would be appreciated.
> highlevel: keep track of created resource to properly close them

- CHANGES
- pyvisa/highlevel.py
- pyvisa/resources/resource.py
This can mitigate issues such as https://github.com/pyvisa/pyvisa/issues/416.
> Do not attempt to close an already closed resources in __del__

- CHANGES
- pyvisa/resources/messagebased.py
> Fix binary read for empty header

- CHANGES
- pyvisa/highlevel.py
- pyvisa/resources/resource.py
Making the open_timeout parameter's documentation compliant with Visa specification. Addresses #446
> Fixing open_timeout parameter documentation

- CHANGES
- docs/source/advanced/architecture.rst
- docs/source/advanced/backends.rst
- docs/source/faq/contributing.rst
- docs/source/faq/faq.rst
- docs/source/faq/getting_nivisa.rst
- docs/source/faq/migrating.rst
- docs/source/index.rst
- docs/source/introduction/communication.rst
- docs/source/introduction/getting.rst
- docs/source/introduction/shell.rst
- pyvisa/cmd_line_tools.py
- pyvisa/highlevel.py
- setup.py
- visa.py
Address https://github.com/pyvisa/pyvisa/issues/447
> Deprecate the visa module

- docs/source/introduction/configuring.rst
- docs/source/introduction/resources.rst
- docs/source/substitutions.sub
> Document how to access the VISA attributes

- docs/source/faq/faq.rst
Update to the FAQ regarding the issue we discussed.
Should cover a number of the steps that were discussed as well as final resolution.
> Issue 538 FAQ Update

- .github/workflows/ci.yml
- CHANGES
- README.rst
- pyvisa/highlevel.py
- pyvisa/testsuite/test_cmd_line_tools.py
- pyvisa/testsuite/test_highlevel.py
> Fix list backends

- docs/source/introduction/event_handling.rst
- docs/source/introduction/example.rst
- docs/source/introduction/resources.rst
- docs/source/introduction/rvalues.rst
This is only a space inserted in the documentation to make it render properly.
> Fix rendering of code

- README.rst
Three minor grammatical and wording changes to the README
This does not impact any open issues and is not a change to software
> minor grammar and wording

- .gitignore
- .pre-commit-config.yaml
- CHANGES
- docs/source/advanced/backends.rst
- pyvisa/constants.py
- pyvisa/highlevel.py
- pyvisa/shell.py
- pyvisa/testsuite/fake-extensions/pyvisa_test_open.py
- pyvisa/testsuite/test_highlevel.py
> Adding support for pyvisa_proxy #660

- docs/source/faq/faq.rst
I have documented in the FAQ how to use PyVISA with Cygwin by setting either a .pyvisarc or by specifying the visaXX.dll
> Extended FAQ to include using PyVISA on Cygwin on Windows.

- .flake8
- .github/workflows/ci.yml
- CHANGES
- pyvisa/__init__.py
- pyvisa/constants.py
- pyvisa/resources/tcpip.py
- pyvisa/rname.py
- pyvisa/testsuite/test_rname.py
@bobmcnamara that should help you get started. I you can find the value for the interface type and tell me what attributes are expected to be supported I can complete this.
> Adding support for VICP resources

- paper.bib
- paper.md
This addresses the discussion over on https://github.com/openjournals/joss-reviews/issues/5304 RE: the DOI for The Cathedral and the Bazaar (c.f. https://github.com/openjournals/joss-reviews/issues/5304#issuecomment-1518546777).
Use the published Springer article as it has a DOI and is archive stable.
- Note that the text probably referenced was from the authors website http://www.catb.org/~esr/writings/cathedral-bazaar/
---
- [N/A] Closes # (insert issue number if relevant)
- [N/A] Executed ``black . && isort -c . && flake8`` with no errors
- [N/A] The change is fully covered by automated unit tests
- [N/A] Documented in docs/ as appropriate
- [N/A] Added an entry to the CHANGES file
> chore: Update 'Cathedral and the Bazaar' reference

- docs/source/faq/faq.rst
- docs/source/introduction/configuring.rst
Small touch-ups triggered by https://github.com/pyvisa/pyvisa-py/issues/376#issuecomment-1580307474
> doc: remove no longer relevant mentions of `visa` module + more bitness fixes

- pyvisa/rname.py
- pyvisa/testsuite/test_rname.py
> rname: fix VICP resource name normalization

- pyvisa/resources/gpib.py
Add a more convenient interface for accessing GPIB commands and improve grou_execute_trigger.
@greyltc if you can test this it would be amazing.
> Gpib commands

- CHANGES
- pyvisa/attributes.py
- pyvisa/constants.py
- pyvisa/resources/serial.py
- pyvisa/resources/tcpip.py
- pyvisa/rname.py
Support added for Prologix GPIB adapters, both USB and ethernet.  Examples of usage:
`    import pyvisa`
`    rm = pyvisa.ResourceManager()`
`    prlgx = rm.open_resource("PRLGX-TCPIP::169.254.1.80::INTFC")`
`    instr = rm.open_resource("GPIB::17::INSTR")`
`    instr.query("*IDN?")`
Or for USB version:
`    import pyvisa`
`    rm = pyvisa.ResourceManager()`
`    prlgx = rm.open_resource("PRLGX-ASRL::/dev/cu.usbserialXXX::INTFC")`
`    instr = rm.open_resource("GPIB::17::INSTR")`
`    instr.query("*IDN?")`
- [n/a] Closes # (insert issue number if relevant)
- [ToDo] The change is fully covered by automated unit tests
- [ToDo] Documented in docs/ as appropriate
> Prologix support for both USB and ethernet versions
